### ISSUE TITLE
Feature  - Use UUID from PE licence.key File as preshared KEY / password for VPN connection

### ISSUE THREAD

**Issue by MartyEwings** [puppetlabs/puppetlabs-puppet_operations_appliance#15]
The VPN connection requires a password that is prepopulated server side. The UUID from the licence.key file on the primary server has the complexity and the uniqueness as well customer association to be this preshared key.

This Feature will:

- On the Primary Server Parse the UUID value from the licence.key file
- The UUID Value must be consumable on a node assigned the rsan::importer class so that it may be compiled in the catalog as a parameter

This Feature does not:
 - Configure openvpn client ( this is another feature for that)

**Comment by timidri** [comment]
@MartyEwings Should I create a function for this? I don't see any other functions in the repo (yet)?
