### ISSUE TITLE
Allow for removal of RSAN on the exporter nodes

### ISSUE THREAD

**Issue by jarretlavallee** [puppetlabs/puppetlabs-puppet_operations_appliance#24]
The module should have a way of removing all of the configuration on the exporter nodes in the case that it needs to be removed.

**Comment by MartyEwings** [comment]
removing just the exporter class reverts:

pg_hba.conf
pg_ident.conf

Thats all the RSAN and the metrics dashboard access removed by default

Assuming the RSAN target node is destroyed on uninstall, it should just be

Remove the RSAN database role/user
Disable NFS server
