### ISSUE TITLE
Test what happens when you remove an exporter

### ISSUE THREAD

**Issue by dylanratcliffe** [puppetlabs/puppetlabs-puppet_operations_appliance#37]
If you had say 4 compilers, all of which had the `rsan::exporter` class applied, then you removed one, what would happen? Would you need to clean up things like NFS mounts?

Maybe not. But we should check and see

**Comment by MartyEwings** [comment]
if you reboot the importer node, it fails to start up at the mounting stage.

I believe the uninstall process I'm just going to call for "trashing" the rsan node, so i don't think we need to consider it.
However now its mentioned I'm concerned we will run into issue  if we remove a compiler or forget a replica... 

I may check if we purge a node, and the exported nfs resource are no longer there, does this remove the mounts on the target node, because that would be ideal

**Comment by jarretlavallee** [comment]
Maybe we should export the nfs mount with the `unmounted` option to ensure `RSAN` removes it. Or is there an NFS option to purge non managed client mounts? I could see issues with a customer provisioning and decommissioning compilers.

**Comment by MartyEwings** [comment]
yeah i had  explored that, i couldnt figure out how to do it selectively, once you remove the node as a compiler, it simply wont have rsan code running on it, we would need a way to purge exported resources and make sure they are removed from the mounting on the rsan node

**Comment by MartyEwings** [comment]
so it turns out this nfs module is using a parameter "intr" in the fstab entry that is supposed to prevent the need to have the server available to boot a machine with the mount, this has been deprecated and no longer does anything in new NFS , so should be overridden with "soft"

**Comment by MartyEwings** [comment]
the following code when applied to the resource collector in the importer class will add the parameter in, and set the retranmission attempts to 1, this will still make a reboot slow, but it will eventually kick out of it and boot after a few mins

```
Nfs::Client::Mount <<| nfstag == 'rsan' |>>

{ options_nfs => 'tcp,nolock,rsize=32768,wsize=32768,soft,noatime,actimeo=3,retrans=1', }
```

there is the possibility of data loss on the nfs mount with a retans of 1, however for log processing this should be ok

**Comment by MartyEwings** [comment]
There will still need to be cleanup,  if a compiler is actually decommissioned (puppet node purge)  the resource will no longer be mounted if not present, but the now defunct mount will not be removed,  and cause delay to rsan node reboots

**Comment by MartyEwings** [comment]
Further testing, this is a self correcting issue, for temporary server down, after a retry period the server restarts without the mount in question.

Puppet runs then re-add the mount when available.

For permanent offline servers, after the first reboot, there will no longer be an exported resource to re-enable the mount,

**Comment by MartyEwings** [comment]
We will need a cleanup task, im not sure how to identify mounts that are no longer valid, we may need to add a task to cleanup fstab for former compilers, However with the timeout this is no longer a catastrophic failure, juts a delay I suggest we make that change
