### ISSUE TITLE
Errors when provisioning a PE replica with rsan already up and running

### ISSUE THREAD

**Issue by pgrant87** [puppetlabs/puppetlabs-puppet_operations_appliance#49]
## Describe the Bug
Working more on SUP-2384 a bit more this morning and all looked good on my single monolithic 20198 nightly master. Moving now to a replica and compilers, I’m getting an error when installing my replica which is coming from the puppet metrics dashboard. So it's failing with:

```
Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Could not find resource 'Service[puppetserver]' in parameter 'notify' (file: /etc/puppetlabs/code/environments/production/modules/puppet_metrics_dashboard/manifests/profile/master/install.pp, line: 18) on node 20198nightlyrep.platform9.puppet.net
```

Which looks like it's failing because the puppetserver hasn’t been installed yet.

This metrics dashboard isn’t something I’ve classified, it applied through RSAN. Could see this also being an issue when adding compilers but I haven't tested this yet.

## Expected Behavior
Be able to provision a repilca and add compilers successfully after Rsan has been deployed

## Steps to Reproduce
1. Set up a master, and rsan on a separate node and confirm functionality.
2. Then try to provision a replica

## Environment
 - Centos 7 machines
 - PE 2019.8 nightly builds

**Comment by MartyEwings** [comment]
Replica_install_fix branch may fix this
