### ISSUE TITLE
rename to puppetlabs-rsan?

### ISSUE THREAD

**Issue by bastelfreak** [puppetlabs/puppetlabs-puppet_operations_appliance#72]
## Use Case

Hi!
all Puppet Inc. owned modules have a git repository named puppetlabs-$name. Would it be possible to rename RSAN to puppetlabs-rsan to stay consistent? I think that would help a lot of automation on the long run.

## Describe the Solution You Would Like

I would like to have a consistent naming scheme for puppet module repositories.

## Describe Alternatives You've Considered

I don't see an alternative to renaming, except for ditching the current naming scheme.

**Comment by MartyEwings** [comment]
I lnow this was a while ago! but yes, probably going to rename this to something other than RSAN and ill make the org prefix in there when i do that

**Comment by MartyEwings** [comment]
renamed entire project, and included the standard naming convention
